### ISSUE TITLE
推荐一个微信小程序可以方便查看该项目

### ISSUE THREAD

**Issue by ZhuPeng** [overnote/over-golang#1]
Hi, 最近开发了一个 GitHub 的微信小程序，可以方便的在手机上查看 GitHub 的相关内容，扫描下方二维码就可以方便查看这个教程~
![image](https://user-images.githubusercontent.com/4994339/57451532-24d25080-7294-11e9-9afb-301532cb039a.png)

小程序是开源的，有任何问题和意见可以直接提 Issue 反馈：[GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)

**Comment by liyuhang1997** [comment]
请不要将 GitHub 作为你发布广告的平台
