### ISSUE TITLE
01-基础语法/06-值类型-2-字符串.md

### ISSUE THREAD

**Issue by zoe-icu** [overnote/over-golang#37]
3.3 字符串连接
 
//创建字节缓冲
var stringBuilder bytes.Buffer

这里是不是应该改成  
var stringBuilder strings.Builder

**Comment by ruyuejun** [comment]
你看的很认真很仔细，我也需要再抽时间回头彻底校正一下

**Comment by betterA** [comment]
这个改了 但是还是改错了 strings.Builder 不是 strings.Buffer

> 你看的很认真很仔细，我也需要再抽时间回头彻底校正一下
