### ISSUE TITLE
错别字集合

### ISSUE THREAD

**Issue by dinjufen** [overnote/over-golang#4]
看的过程中发现了一些错别字：
1. Golang/02-Go并发编程/00-并发简略3-多线程编程.md：
   “线程自己私有的数据都存储在线程栈中，**咸成展**位于所属进程的虚拟内存地址中”，应为“线程 
   栈”

**Comment by ruyuejun** [comment]
感谢 @dinjufen ，最近在忙着Go的数据结构与算法笔记，今天开始继续维护golang笔记，又要有一大波更新来了

**Comment by dinjufen** [comment]
golang/03-Go并发编程/04-并发原理1-线程模型.md
3.2 P 第六行 “海油”->还有

**Comment by dinjufen** [comment]
golang/03-Go并发编程/04-并发原理1-线程模型.md
3.2 P 第7行 “舒朗”->数量

**Comment by ph0enix8** [comment]
golang/03-Go并发编程/00-简略1-并发概述.md 
3.1 进程 最后一句“它的父进程需要调用系统取得子基础南横终止态。” -> 它的父进程需要调用系统取得子进程的终止态。

**Comment by ph0enix8** [comment]
golang/03-Go并发编程/00-简略2-多进程编程.md 
1.2 进程的衍生 
第6段
      “Unix系系统每个进程都有父进程” -> “Unix系统每个进程都有父进程”
      "内核启动基础进程是进城树的根" ->”内核启动基础进程是进程树的根“
第7段
     “字进程将会被内核启动进程收养” -> “子进程将会被内核启动进程收养 ”

**Comment by ruyuejun** [comment]
近期微服务相关在制作中，上述错误将会和微服务知识点一起update

**Comment by zhongqin0820** [comment]
02-Go语法/07-复合类型1-数组.md

**Comment by williammmmmmmmm** [comment]
golang/03-Go并发编程/00-简略2-多进程编程
1.6
进程的切换和调度"室"多程序并发执行的基础。 ->是？

**Comment by APOLLO2333** [comment]
golang/02-Go语法/14-反射.md   二/2.1
Type是系统原生数据类型： int、 string、 boo!、 float32 ，以及 type 定义的类型
其中bool型的l变成了!感叹号
