### ISSUE TITLE
在01-基础语法；06-值类型-2-字符串.md

### ISSUE THREAD

**Issue by swordGhostKing** [overnote/over-golang#41]
使用+能够连接字符串。但是该操作并不高效（因为字符串在Go中是基本类型，每次拼接都是拷贝了内存！）。Go1.10提供了类似Java的StringBuilder机制来进行高效字符串连接；
叙述没问题；
但是代码里面写成了
var stringBuilder strings.Buffer
应该是
var stringBuilder strings.Builder

**Comment by ruyuejun** [comment]
感谢
